# Generated by Django 2.0.7 on 2018-07-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBreno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaSenha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=50, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
