# Generated by Django 2.0.7 on 2018-07-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBreno', '0002_tabelasenha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelasenha',
            name='perguntinha',
            field=models.TextField(blank=True, null=True),
        ),
    ]
