# Generated by Django 2.0.7 on 2018-07-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBreno', '0003_tabelasenha_perguntinha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelasenha',
            name='senha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
